JobSite/Controllers/HomeController.cs
using BusinessLayer.Abstract;
using DataAccessLayer.Data;
using EntityLayer.Entities;
using JobSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace JobSite.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWorkService _workService;

        public HomeController(ICategoryService categoryService, IFieldService fieldService, 
            ICityService cityService, IWorkService workService, ApplicationDbContext context)
            : base (fieldService, cityService, categoryService)
        {
            _context = context;
            _workService = workService;
        }
        public async Task<JsonResult> GetCategories(int id)
        {
            return await GetCategoriesAsync(id);
        }
        private async Task SetDropdown()
        {
            await SetDropdownAsync();
        }

        [HttpPost]
        public IActionResult Filtr(FiltrModel data)
        {
            IQueryable<Work> query = _context.Works.Include(x => x.Field).Include(x => x.City);

            if (data.FieldId.HasValue)
                query = query.Where(x => x.FieldId == data.FieldId);
            if (data.CategoryId.HasValue)
                query = query.Where(x => x.CategoryId == data.CategoryId);
            if (data.CityId.HasValue)
                query = query.Where(x => x.CityId == data.CityId);
            if (data.WorkExprience != null)
                query = query.Where(x => x.WorkExperience == data.WorkExprience);
            if (data.Education != null)
                query = query.Where(x => x.Education == data.Education);
            if (data.MinSalary != null)
                query = query.Where(x => x.Salary >= data.MinSalary);

            var result = query.ToList();
            return View(result);
        }

        public async Task<IActionResult> WorksInFieldId(int id)
        {
            var worksInFieldId = await _workService.SGetWorksWithIncludesAsync(new[] { "City", "Field" }, x => x.FieldId == id);
            var field = _context.Fields.Where(x => x.Id == id).First();
            ViewBag.FieldName = field.Name;
            return View(worksInFieldId);
        }

        public async Task<IActionResult> Index()
        {
            await SetDropdown();
            return View();
        }
    }
}

JobSite/Controllers/JobsController.cs
using BusinessLayer.Abstract;
using DataAccessLayer.Data;
using EntityLayer.Entities;
using JobSite.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace JobSite.Controllers
{
    public class JobsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWorkService _workService;

        public JobsController(ICategoryService categoryService, IFieldService fieldService,
            ICityService cityService, IWorkService workService, ApplicationDbContext context)
            : base(fieldService, cityService, categoryService)
        {
            _context = context;
            _workService = workService;
        }
        public async Task<JsonResult> GetCategories(int id)
        {
            return await GetCategoriesAsync(id);
        }
        private async Task SetDropdown()
        {
            await SetDropdownAsync();
        }


        [HttpGet]
        public IActionResult Filtr(int? FieldId, int? CategoryId, int? CityId, string? Education, string? WorkExprience, int? MinSalary)
        {
            IQueryable<Work> query = _context.Works;

            if (FieldId.HasValue)
                query = query.Where(x => x.FieldId == FieldId);
            if (CategoryId.HasValue)
                query = query.Where(x => x.CategoryId == CategoryId);
            if (CityId.HasValue)
                query = query.Where(x => x.CityId == CityId);
            if (WorkExprience != null)
                query = query.Where(x => x.WorkExperience == WorkExprience);
            if (Education != null)
                query = query.Where(x => x.Education == Education);
            if (MinSalary != null)
                query = query.Where(x => x.Salary >= MinSalary);

            var result = query.Select(x => new
            {
                x.Id,
                x.Position,
                x.Salary,
                x.ModeOfWork,
                x.IsNegotiable,
                fieldName = x.Field.Name,
                fieldIcon = x.Field.Icon,
                cityName = x.City.Name
            }).ToList();

            return Json(result);
        }

        public async Task<IActionResult> Index()
        {
            await SetDropdown();
            return View();
        }

        public IActionResult JobDetails(int id)
        {
            var work = _context.Works
                .Include(x => x.City).Include(x => x.Field).Include(x => x.Category)
                .Where(x => x.Id == id).FirstOrDefault();
            return View(work);
        }

    }
}

JobSite/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>About</h1>

JobSite/Views/Home/Filtr.cshtml
@{
    ViewData["Title"] = "Filtr";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Work>

    <style>
        .boxes {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap:20px;
        }
        .box {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid #888;
            border-radius: 10px;
            padding:15px;
            box-shadow: 0 2px 4px #9999;
            transition: 0.3s;
        }

        .box .heart {
            position: absolute;
            width: 35px;
            height:35px;
            font-size:18px;
            top: 3px;
            right: 3px;
            background: #fff;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #83B5FE !important;
            cursor: pointer;
        }

        .box .heart:hover {
                background: #83B5FE;
                color: #fff !important;
        }
        .box h4{
            margin-top:10px;
        }
        .box .more {
            gap: 12px;
        }
        .box .more p i {
            color: #83B5FE;
        }
        .meBut {
            transition: 0.2s;
            padding:5px 10px;
            border-radius:10px;
            border: 1px solid #444;
            cursor: pointer;
            color: #444;
            background: #fff;
        }
        .meBut:hover {
            background: #83B5FE;
            color: #fff;
            border-color: #83B5FE;
        }
        .box:hover {
            border-color: #83B5FE;
            transform: translateY(-10px);
        }
    </style>

<div style="padding:50px; margin-top:100px">
    @if (Model.Count == 0)
    {
        <h2>İş elanı tapılmadı</h2>
    }
    else
    {
        <h2>@Model.Count nəticə</h2>
        <br />
        <div class="boxes">
            @foreach (var w in Model)
            {
                <div class="box">
                    <a class="heart"><i class="ti-heart"></i></a>
                    <div class="icon"><i class="@w.Field.Icon"></i></div>
                    <h4>@w.Position</h4>
                    <div class="d-flex align-items-center more">
                        <p><i class="fa-solid fa-location-dot"></i> @w.City.Name</p>
                        <p><i class="fa fa-clock-o"></i> @w.ModeOfWork</p>
                        @if (!w.IsNegotiable)
                        {
                            <p><i class="fa-solid fa-manat-sign"></i> @w.Salary</p>
                        }
                        else
                        {
                            <p><i class="fa-solid fa-manat-sign"></i> Razılaşma</p>
                        }
                    </div>
                    <p>@w.PublishDate</p>
                    <a asp-controller="Jobs" asp-action="JobDetails" asp-route-id="@w.Id" class="meBut">ㅤƏtraflıㅤ</a>
                </div>
            }
        </div>
    }
</div>

JobSite/Views/Home/WorksInFieldId.cshtml
@{
    ViewData["Title"] = "WorksInFieldId";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model List<Work>

    <style>
        .boxes {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap:20px;
        }
        .box {
            display: flex;
            flex-direction: column;
            align-items: center;
            border: 1px solid #888;
            border-radius: 10px;
            padding:15px;
            box-shadow: 0 2px 4px #9999;
            transition: 0.3s;
        }

        .box .heart {
            position: absolute;
            width: 35px;
            height:35px;
            font-size:18px;
            top: 3px;
            right: 3px;
            background: #fff;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #83B5FE !important;
            cursor: pointer;
        }
        .box .heart:hover {
                background: #83B5FE;
                color: #fff !important;
        }
        .box h4{
            margin-top:10px;
        }
        .box .more {
            gap: 12px;
        }
        .box .more p i {
            color: #83B5FE;
        }
        .meBut {
            transition: 0.2s;
            padding:5px 10px;
            border-radius:10px;
            border: 1px solid #444;
            cursor: pointer;
            color: #444;
            background: #fff;
        }
        .meBut:hover {
            background: #83B5FE;
            color: #fff;
            border-color: #83B5FE;
        }
        .box:hover {
            border-color: #83B5FE;
            transform: translateY(-10px);
        }
    </style>

<div style="padding:50px; margin-top:100px">
    @if (Model.Count == 0)
    {
        <h2><span style="color: #83B5FE">@ViewBag.FieldName</span> kateqoriyasına uyğun iş elanı tapılmadı</h2>
    }
    else
    {
        <h2><span style="color: #83B5FE">@ViewBag.FieldName</span> kateqoriyasına uyğun @Model.Count nəticə</h2>
        <br />
        <div class="boxes">
            @foreach (var w in Model)
            {
                <div class="box">
                    <a class="heart"><i class="ti-heart"></i></a>
                    <div class="icon"><i class="@w.Field.Icon"></i></div>
                    <h4>@w.Position</h4>
                    <div class="d-flex align-items-center more">
                        <p><i class="fa-solid fa-location-dot"></i> @w.City.Name</p>
                        <p><i class="fa fa-clock-o"></i> @w.ModeOfWork</p>
                        @if (!w.IsNegotiable)
                        {
                            <p><i class="fa-solid fa-manat-sign"></i> @w.Salary</p>
                        }
                        else
                        {
                            <p><i class="fa-solid fa-manat-sign"></i> Razılaşma</p>
                        }
                    </div>
                    <p>@w.PublishDate</p>
                    <a asp-controller="Jobs" asp-action="JobDetails" asp-route-id="@w.Id" class="meBut">ㅤƏtraflıㅤ</a>
                </div>
            }
        </div>
    }
</div>