JobSite/Areas/Admin/Controllers/CandidateController.cs
using BusinessLayer.Abstract;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace JobSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "AdminPolicy")]
    public class CandidateController : Controller
    {
        private readonly ICandidateService _candidateService;
        private readonly ICityService _cityService;
        private readonly IFieldService _fieldService;
        private readonly ICategoryService _categoryService;
        private readonly IUserService _userService;

        public CandidateController(ICandidateService candidateService, 
            ICityService cityService, IFieldService fieldService, ICategoryService categoryService, IUserService userService)
        {
            _candidateService = candidateService;
            _cityService = cityService;
            _fieldService = fieldService;
            _categoryService = categoryService;
            _userService = userService;
        }

        private async Task<List<Field>> GetFields()
        {
            var fields = await _fieldService.SGetAllAsync(x => x.IsActive);
            return fields;
        }
        private async Task<List<City>> GetCities()
        {
            var cities = await _cityService.SGetAllAsync(x => x.IsActive);
            return cities;
        }
        public async Task<JsonResult> GetCategories(int id)
        {
            var categories = await _categoryService.SGetAllAsync(x => x.FieldId == id && x.IsActive);
            return Json(categories);
        }

        private async Task Dropdown()
        {
            var fields = await GetFields();
            var cities = await GetCities();
            ViewBag.Fields = new SelectList(fields, "Id", "Name");
            ViewBag.Cities = new SelectList(cities, "Id", "Name");
        }
        private async Task Dropdown(Candidate candidate)
        {
            var fields = await GetFields();
            var cities = await GetCities();
            var categories = await _categoryService.SGetAllAsync(x => x.FieldId == candidate.FieldId);
            ViewBag.Fields = new SelectList(fields, "Id", "Name");
            ViewBag.Cities = new SelectList(cities, "Id", "Name");
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
        }

        public async Task<JsonResult> GetCandidateInfo(int wId, string type)
        {
            var candidate = await _candidateService.SReadAsync(wId);
            var data = type switch
            {
                "EducationMore" => candidate.EducationMore,
                "WorkExperienceMore" => candidate.WorkExperienceMore,
                "Skills" => candidate.Skills,
                "AddInformation" => candidate.AddInformation,
                _ => string.Empty
            };
            return Json(new
            {
                fullName = candidate.Firstname + " " + candidate.Lastname + " " + candidate.Patronymic,
                data
            });
        }

        //Index

        public async Task<IActionResult> Index()
        {
            var candidates = await _candidateService.SGetCandidatesWithIncludesAsync(new[] { "Field", "City", "User", "Category" });
            return View(candidates);
        }

        //Create 

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.userId = _userService.GetUserId();
            await Dropdown();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Candidate data, IFormFile? pImage)
        {
            if (ModelState.IsValid)
            {
                if (pImage != null)
                {
                    var extension = Path.GetExtension(pImage.FileName);
                    var uniqueImgName = Guid.NewGuid().ToString() + extension;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pImage/", uniqueImgName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await pImage.CopyToAsync(stream);
                    }
                    data.Image = "/pImage/" + uniqueImgName;
                }
                else data.Image = "/pImage/defaultUserImage.png";

                data.IsActive = true;
                data.PublishDate = DateTime.Now;
                data.EndDate = DateTime.Now.AddDays(30);
                await _candidateService.SCreateAsync(data);
                TempData["createdSuccessfully"] = "Created successfully";
                return RedirectToAction(nameof(Index), "Candidate", new { area = "Admin" });
            }
            ViewBag.userId = _userService.GetUserId();
            await Dropdown(data);
            return View(data);
        }

        //Update

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var upItem = await _candidateService.SReadAsync(id);
            ViewBag.ExistingImageUrl = upItem.Image;
            await Dropdown(upItem);
            return View(upItem);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Candidate upData, IFormFile? pImage)
        {
            if (ModelState.IsValid)
            {
                if (pImage != null)
                {
                    var extension = Path.GetExtension(pImage.FileName);
                    var uniqueImgName = Guid.NewGuid().ToString() + extension;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/pImage/", uniqueImgName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await pImage.CopyToAsync(stream);
                    }
                    upData.Image = "/pImage/" + uniqueImgName;
                }
                else upData.Image = Request.Form["existingImageUrl"];

                //upData.IsActive = true;
                await _candidateService.SUpdateAsync(upData);
                TempData["updatedSuccessfully"] = "Updated successfully";
                return RedirectToAction(nameof(Index), "Candidate", new { area = "Admin" });
            }
            var upItem = await _candidateService.SReadAsync(upData.Id);
            ViewBag.ExistingImageUrl = upItem.Image;
            await Dropdown(upData);
            return View(upData);
        }

        //Delete

        [HttpDelete]
        public async Task<JsonResult> Delete(int id)
        {
            var deleteItem = await _candidateService.SReadAsync(id);
            await _candidateService.SDeleteAsync(deleteItem);
            return Json(new { success = true, message = "Deleted successfully" });
        }
    }
}

JobSite/Controllers/CandidatesController.cs
using BusinessLayer.Abstract;
using DataAccessLayer.Data;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JobSite.Controllers
{
    public class CandidatesController : BaseController
    {
        private readonly ICandidateService _candidateService;
        private readonly ApplicationDbContext _context;

        public CandidatesController(ICategoryService categoryService, IFieldService fieldService,
            ICityService cityService, ICandidateService candidateService, ApplicationDbContext applicationDbContext)
            : base (fieldService, cityService, categoryService)
        {
            _candidateService = candidateService;
            _context = applicationDbContext;
        }
        public async Task<JsonResult> GetCategories(int id)
        {
            return await GetCategoriesAsync(id);
        }
        private async Task SetDropdown()
        {
            await SetDropdownAsync();
        }

        public async Task<IActionResult> Index()
        {
            var candidates = _context.Candidates.Where(x =>x.IsActive).Include(x=>x.City).ToList();
            await SetDropdown();
            return View(candidates);    
        }

        [HttpGet]
        public async Task<IActionResult> Filtr(int? FieldId, int? CategoryId, int? CityId, string? Education, string? WorkExprience, int? MaxSalary)
        {
            IQueryable<Candidate> query = _context.Candidates;
            if (FieldId.HasValue)
                query = query.Where(x => x.FieldId == FieldId);
            if (CategoryId.HasValue)
                query = query.Where(x=>x.CategoryId == CategoryId);
            if (CityId.HasValue)
                query = query.Where(x=>x.CityId == CityId);
            if (!string.IsNullOrWhiteSpace(Education))
                query = query.Where(x => x.Education == Education);
            if (!string.IsNullOrWhiteSpace(WorkExprience))
                query = query.Where(x => x.WorkExperience == WorkExprience);
            if (MaxSalary.HasValue)
                query = query.Where(x => x.MinSalary <= MaxSalary);

            var result = query.Select(x => new
            {
                x.Id,
                x.Position,
                x.Firstname,
                x.Lastname,
                x.MinSalary,
                x.Age,
                x.Image,
                x.WorkExperience,
                x.Education,
                cityName = x.City.Name
            }).ToList();
            return Json(result);
        }

        public IActionResult Details(int id)
        {
            var item = _context.Candidates.Where(x=>x.Id==id).Include(x=>x.City).Include(x=>x.Field).Include(x=>x.Category).FirstOrDefault();
            return View(item);
        }
    }
}

JobSite/Views/Candidates/Details.cshtml
@model Candidate
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string tel = Model.Phone.ToString().Substring(1);
}

<div class="job_details_area">
    <div class="job_details">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between align-items-center" style="border-radius: 10px;">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb" style="padding: 0">
                                <img style="border-radius: 5px" src="@Model.Image" width="80" height="80" alt="" />
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>@Model.Position - <span style="color: forestgreen">@Model.Firstname @Model.Lastname @Model.Patronymic</span></h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <div class="job_content_item">
                                            <div class="job_content_item_text">
                                                <p>elan tarixi</p>
                                                <span>@Model.PublishDate.ToString("dd.MM.yyyy")</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="location">
                                        <div class="job_content_item">
                                            <div class="job_content_item_text">
                                                <p>bitmə tarixi</p>
                                                <span>@Model.EndDate.ToString("dd.MM.yyyy")</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#">
                                    <i class="ti-heart"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg" style="border-radius: 10px; margin-top: 5px;">
                    <div class="single_wrap">
                        <h4>Bacarıqlar</h4>
                        @Html.Raw(Model.Skills)
                    </div>
                    <div class="single_wrap">
                        @if(Model.EducationMore != null)
                        {
                            <h4>Ətraflı (Təhsil)</h4>
                            @Html.Raw(Model.EducationMore)
                        }
                    </div>
                    <div class="single_wrap">
                        @if(Model.WorkExperienceMore != null)
                        {
                            <h4>Ətraflı (İş təcrübəsi)</h4>
                            @Html.Raw(Model.EducationMore)
                        }
                    </div>
                    <div class="single_wrap">
                        @if(Model.AddInformation != null)
                        {
                            <h4>Ətraflı (Mütəxəssis)</h4>
                            @Html.Raw(Model.AddInformation)
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>İş məlumatları</h3>
                    </div>
                    <div class="job_content">
                        <div class="job_content_item">
                            <div class="job_content_item">
                                <i class="fas fa-briefcase"></i>

                                <div class="job_content_item_text ml-2">
                                    <p>sahə</p>
                                    <span>@Model.Field.Name</span>
                                </div>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <div class="job_content_item">
                                <i class="fa-solid fa-layer-group"></i>
                                <div class="job_content_item_text ml-2">
                                    <p>kateqoriya</p>
                                    <span>@Model.Category.Name</span>
                                </div>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fa-solid fa-location-dot"></i>
                            <div class="job_content_item_text ml-2">
                                <p>şəhər</p>
                                <span>@Model.City.Name</span>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fas fa-calendar"></i>
                            <div class="job_content_item_text ml-2">
                                <p>yaş</p>
                                <span>@Model.Age</span>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fa-solid fa-graduation-cap"></i>
                            <div class="job_content_item_text ml-2">
                                <p>təhsil</p>
                                <span>@Model.Education</span>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fa-solid fa-business-time"></i>
                            <div class="job_content_item_text ml-2">
                                <p>iş təcrübəsi</p>
                                <span>@Model.WorkExperience</span>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fa-solid fa-venus-mars"></i>
                            <div class="job_content_item_text ml-2">
                                <p>Cins</p>
                                <span>@Model.Gender</span>
                            </div>
                        </div>
                        <div class="job_content_item">
                            <i class="fa-solid fa-sack-dollar"></i>
                            <div class="job_content_item_text ml-2">
                                <p>Min. Əmək haqqı</p>
                                <span>@Model.MinSalary azn</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="job_sumary mt-3">
                    <div class="summery_header">
                        <h3>Əlaqə məlumatları</h3>
                    </div>
                    <div class="job_content">
                        <div class="job_content_item d-block">
                            <div class="job_content_item">
                                <i class="fa-regular fa-envelope"></i>
                                <div class="job_content_item_text ml-2">
                                    <p>email</p>
                                    <a href="mailto:@Model.Email">@Model.Email</a>
                                </div>
                            </div>
                            <div class="job_content_item mt-3">
                                <i class="fa-solid fa-phone"></i>
                                <div class="job_content_item_text ml-2">
                                    <p>telefon</p>
                                    <a href="tel:@tel">@Model.Phone</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="share_wrap d-flex mt-3">
                    <span>Paylaş</span>
                    <ul>
                        <li>
                            <a href="https://api.whatsapp.com/send?text=İlan%20Bağlantısı%20burada" target="_blank"> <i class="fa-brands fa-whatsapp"></i></a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/" target="_blank"> <i class="fa-brands fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="mailto:?subject=İlan Başlığı&body=İlan%20Bağlantısı%20burada" target="_blank"> <i class="fa-regular fa-envelope"></i></a>
                        </li>
                        <li>
                            <a href="#"> <i class="fa-brands fa-facebook"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

JobSite/Views/Candidates/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<Candidate>

<style>
    .listPage {
        padding: 10px;
        text-align: center;
        list-style: none;
    }

        .listPage li {
            background-color: #fff;
            border: 1px solid #83B5FE;
            color: #83B5FE;
            display: inline-block;
            margin: 0 10px;
            cursor: pointer;
            padding: 7px;
            width: 40px;
            border-radius: 50%;
        }

        .listPage .active {
            background-color: #83B5FE;
            color: #fff;
        }
    .thumb img {
        width: 70px !important;
        height: 70px;
    }
    .custom-shape-divider-bottom-1727869364 {
        position: absolute;
        bottom: -1px;
        left: 0;
        width: 100%;
        overflow: hidden;
        line-height: 0;
        transform: rotate(180deg);
    }

        .custom-shape-divider-bottom-1727869364 svg {
            position: relative;
            display: block;
            width: calc(108% + 1.3px);
            height: 79px;
        }

        .custom-shape-divider-bottom-1727869364 .shape-fill {
            fill: #FFFFFF;
        }

    .form-container {
        padding: 76px;
        width: 100%;
        text-align: center;
    }
    .form-container button {
        width: 200px;
        margin-top: 30px;
    }
    .form-container div{
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        display: grid;
    }
    .form-container div select, .form-container div input {
        padding: 10px;
        outline: none;
        border: 1px solid #888;
        border-radius: 5px;
        cursor: pointer;
        overflow-y: auto;
        color: #555;
    }
    .form-container div input::placeholder {
        color: #555;
    }
    .form-container div select:focus, .form-container div input:focus {
        border-color: cornflowerblue;
    }

    .form-container div select::-webkit-scrollbar {
        width: 8px; 
    }

    .form-container div select::-webkit-scrollbar-thumb {
        background-color: #9999; 
        border-radius: 4px; 
    }

    .form-container div select::-webkit-scrollbar-track {
        background: #f1f1f1; 
    }

    .single_candidates_index:hover{
        border-color: #83b5fe;
    }

    .single_candidates_index:hover a .thumb img {
        transform: translateY(-5px);
    }

</style>

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="bradcam_area_alt">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h2 style="color: #83b5fe">İş axtaranlar</h2>
                    <h3>@Model.Count+ mövcud CV</h3>
                    <p>Yeni mütəxəssisinizi qarşılayın</p>
                </div>
                <div class="bradcam_img">
                    <img src="~/JobSite/img/candiateds/candidateBradcamArea.webp"
                         width="360"
                         alt="candidateJob" />
                </div>
            </div>
        </div>
    </div>
</div>

<!-- catagory_area -->
<form class="form-container" method="get" autocomplete="off">
    <div>
        <select id="fieldDropdown">
            <option value="" selected>Sahə</option>
            @foreach (var f in ViewBag.Fields)
            {
                <option value="@f.Value">@f.Text</option>
            }
        </select>
        <select id="categoryDropdown">
            <option value="" selected>Kateqoriya</option>
        </select>
        <select id="CityId">
            <option value="" selected>Şəhər</option>
            @foreach (var c in ViewBag.Cities)
            {
                <option value="@c.Value">@c.Text</option>
            }
        </select>
        <select id="Education">
            <option value="" selected>Təhsil</option>
            <option value="Elmi dərəcə">Elmi dərəcə</option>
            <option value="Ali">Ali</option>
            <option value="Natamam ali">Natamam ali</option>
            <option value="Orta texniki">Orta texniki</option>
            <option value="Orta">Orta</option>
        </select>
        <select id="WorkExprience">
            <option value="" selected>İş təcrübəsi</option>
            <option value="1 ildən aşağı">1 ildən aşağı</option>
            <option value="1 ildən 3 ilə qədər">1 ildən 3 ilə qədər</option>
            <option value="3 ildən 5 ilə qədər">3 ildən 5 ilə qədər</option>
            <option value="5 ildən artıq">5 ildən artıq</option>
        </select>
        <!-- Input sahəsi -->
        <input id="MaxSalary" type="number" placeholder="Max. Maaş" />
    </div>

    <button id="filtrButton" type="button" class="boxed-btn3">Mütəxəssis axtar</button>
</form>
<script>

    $(document).ready(function () {
        $('#fieldDropdown').change(function () {
            var fieldId = $(this).val();
            console.log(fieldId)
            $('#categoryDropdown').empty();

            if (fieldId) {
                $.ajax({
                    url: '/Candidates/GetCategories',
                    type: 'GET',
                    data: { id: fieldId },
                    success: function (data) {
                        console.log(data);
                        $('#categoryDropdown').append('<option value="">Kateqoriya</option>');
                        $.each(data, function (index, category) {
                            $('#categoryDropdown').append('<option value="' + category.id + '">' + category.name + '</option>');
                        });
                    },
                    error: function () {
                        alert('Category-lər yüklənərkən xəta baş verdi.');
                    }
                });
            } else {
                $('#categoryDropdown').append('<option value="">Kateqoriya</option>');
            }
        });
    });

</script>
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area candidate_page_padding">
    <div class="featured_candidates">
        <h2 style="margin-top: -20px; margin-bottom: 50px;">İş axtarışında olan mütəxəssislər</h2>
        <div class="row cList">
            @foreach (var c in Model)
            {
                
                <a asp-controller="Candidates" asp-action="Details" asp-route-id="@c.Id" class="col-md-6 col-lg-3 item">
                    <div class="single_candidates">
                        <div class="thumb">
                            <img src="@c.Image" alt="img" />
                            <h4>@c.Position</h4>
                        </div>
                        <p>
                            @c.Firstname @c.Lastname, @c.Age yaş, təhsil @c.Education, iş təcrübəsi @c.WorkExperience,
                            yaşadığım şəhər - @c.City.Name, @c.MinSalary AZN məbləğdən az olmayan
                            maaşa iddialıyam
                        </p>
                    </div>
                </a>
                
            }
        </div>
        <ul class="listPage">
        </ul>
    </div>
</div>

<!--Filtr-->
<script>
    const btn = document.querySelector("#filtrButton");
    btn.addEventListener("click", (e) => {

        let field = document.querySelector("#fieldDropdown").value;
        let category = document.querySelector("#categoryDropdown").value;
        let city = document.querySelector("#CityId").value;
        let education = document.querySelector("#Education").value;
        let workExprience = document.querySelector("#WorkExprience").value;
        let maxSalary = document.querySelector("#MaxSalary").value;
        maxSalary = maxSalary ? parseInt(maxSalary) : null;

        const cList = document.querySelector(".cList");
        const listPage = document.querySelector(".listPage");

        $.ajax({
            type: "GET",
            url: "/Candidates/Filtr",
            data: {
                FieldId: field,
                CategoryId: category,
                CityId: city,
                Education: education,
                WorkExprience: workExprience,
                MaxSalary: maxSalary
            },
            success: function (response) {
                console.log(response);
                cList.innerHTML = "";
                if (response.length == 0) {
                    cList.innerHTML = "<p style='font-size: 20px'>Mütəxəssis tapılmadı</p>";
                    listPage.style.display = "none";
                }
                else {
                    response.forEach((c) => {
                        let item = `<a href="/Candidates/Details/${c.id}" class="col-md-6 col-lg-3 item">
                        <div class="single_candidates">
                            <div class="thumb">
                                    <img src="${c.image}" alt="img" />
                                    <h4>${c.position}</h4>
                            </div>
                            <p>
                                ${c.firstname} ${c.lastname}, ${c.age} yaş, təhsil ${c.education}, iş təcrübəsi ${c.workExperience},
                                yaşadığım şəhər - ${c.cityName}, ${c.minSalary} AZN məbləğdən az olmayan
                                maaşa iddialıyam
                            </p>
                        </div>
                    </a>`;
                        cList.innerHTML += item;
                    });
                    listPage.style.display = "block";
                }
            },
            error: function (error) {
                console.error("Xəta baş verdi:", error);
            }
        });
        //return false;
    });
</script>


<!--Pagination js-->
<script>
    let thisPage = 1;
    let limit = 8;
    let list = document.querySelectorAll('.row .item');

    function loadItem() {
        let beginGet = limit * (thisPage - 1);
        let endGet = limit * thisPage - 1;
        list.forEach((item, key) => {
            if (key >= beginGet && key <= endGet) {
                item.style.display = 'block';
            } else {
                item.style.display = 'none';
            }
        })
        listPage();
    }
    loadItem();
    function listPage() {
        let count = Math.ceil(list.length / limit);
        document.querySelector('.listPage').innerHTML = '';

        if (thisPage != 1) {
            let prev = document.createElement('li');
            prev.innerText = 'PREV';
            prev.style.width = '50px';
            prev.style.borderRadius = '40px';
            prev.setAttribute('onclick', "changePage(" + (thisPage - 1) + ")");
            document.querySelector('.listPage').appendChild(prev);
        }

        for (i = 1; i <= count; i++) {
            let newPage = document.createElement('li');
            newPage.innerText = i;
            if (i == thisPage) {
                newPage.classList.add('active');
            }
            newPage.setAttribute('onclick', "changePage(" + i + ")");
            document.querySelector('.listPage').appendChild(newPage);
        }

        if (thisPage != count) {
            let next = document.createElement('li');
            next.innerText = 'NEXT';
            next.style.width = '50px';
            next.style.borderRadius = '40px';
            next.setAttribute('onclick', "changePage(" + (thisPage + 1) + ")");
            document.querySelector('.listPage').appendChild(next);
        }
    }
    function changePage(i) {
        thisPage = i;
        loadItem();
    }
</script>